### PR TITLE
Release v3.0.0

### PR DESCRIPTION
**Pull request by lpatino10**
This PR contains changes for the next major release: v3.0.0.

Being a major release, there were some hiccups with using an exact generator/API definitions hash. Primarily, I had to make some changes in the Apex generator that, at the time of this writing, are not yet merged. The closest commits at this time though are:
- Codegen: `8dc2602de0f9555623a4721e51c48622a14cfdf5`
- API definition: `5d64e0df520d5620ab7bfd6cae9da917734918d7`

This version comes with a lot of changes in the form of renamed getters/setters, due to naming convention changes in how we're generating the SDK. Things that were previously marked as deprecated were also removed and both Conversation and Language Translator v2 are no longer present.

Full migration details can be found in the [migration guide](https://github.com/watson-developer-cloud/salesforce-sdk/wiki/Migration-Guide#version-300).

### CODE REVIEW

**Comment by germanattanasio** [comment]
Can you add the migration guide as part of this PR?

**Comment by lpatino10** [comment]
Yep, I'm writing it now and will add it once it's done.

**Comment by lpatino10** [comment]
@germanattanasio The migration guide can be found [here](https://github.com/watson-developer-cloud/salesforce-sdk/wiki/Migration-Guide#version-300) and will be linked in the release.

**Comment by germanattanasio** [comment]
Please make sure you do a quick "salesforce" search in our backlog and validate there are no more issues we can fix with this major release.

Good job here 👍

**Comment by lpatino10** [comment]
@mediumTaj everything should be good to review now. The last changes I added were the fixes for the Discovery parameter issue and the generated `createClassifier()/updateClassifier()` code. The migration guide has been updated accordingly.

**Pull request merged**
