### PR TITLE
Release v2.8.0

### PR DESCRIPTION
**Pull request by lpatino10**
This PR contains changes for the v2.9.0 release. This was generated using the following commits:
- Codegen: `f0f4bd2be4a8d0e52a97f6df0d74f2f864d60499`
- API definition: `8e785da94f0c8d62ade5f8c54c1b73447b9aa321`

Full details will be in the changelog upon release.

This PR should be totally ready once production credentials for Assistant v2 can be added to Travis.

### CODE REVIEW

**Comment by mediumTaj** [comment]
Does this include self signed cert feature?

**Comment by lpatino10** [comment]
No, this is just the API changes. I haven't started working on that feature yet but I can hold off on this release until those are done if you want.

**Comment by mediumTaj** [comment]
If it’s easy enough to get in this release that would be good. Not 100% necessary but you will need it in there to validate icp connectivity

**Comment by mediumTaj** [comment]
@lpatino10 there is a build failing

**Comment by lpatino10** [comment]
Yeah that's the Discovery endpoint that seems to be down. I'll clear that up along with a commit explaining the certificates, which is handled in the Salesforce UI.

**Pull request merged**
